// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SBR_GridCombat","status":true,"description":"A combat modification for SBRif... that attaches a grid-based positioning system to combat","parameters":{}}
];
